version: 2.1
jobs:
  bobby:
    docker:
      - image: cimg/ruby:2.7.1-node
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: cimg/ruby:2.7.1-node
    steps:
      - checkout
      - run: echo "Double trouble2"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
