version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm i
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm i
      - run: npm test
workflows:
  version: 2
  build_test_and_ling:
    jobs:
      - build
      - hithere
      - test
